# Version of Docker-compose
# prettier-ignore
version: '1.0'
services:
  server:
      env_file: '.env'
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - 5000:5000
      # volumes:
      #   - nodeVolume:/src/app/server
  frontend:
    build: ./client
    # volumes:
    #   - ./client:/client
    #   - /client/node_modules
    ports:
      - 3000:3000
    # environment:
    #   - CHOKIDAR_USEPOLLING=true
    depends_on:
      - server
# volumes:
#   nodeVolume:
